# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
