# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171020_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
